// <auto-generated />
namespace NBL_USA.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class TeamCorrections : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TeamCorrections));
        
        string IMigrationMetadata.Id
        {
            get { return "202107300124323_TeamCorrections"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
